Repository Synapxe-DNA/azure-conversational-assistant, pull requests merged in 2024-08, with the labels that each got.

#26 Frontend convo broker
  app/frontend-healthier-me/src/app/services/chat-message/chat-message.service.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.spec.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/types/profile.type.ts
  app/frontend-healthier-me/src/app/types/responses/chat-response.type.ts
  app/frontend-healthier-me/src/app/types/responses/response-status.type.ts
  app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts
Labels: enhancement

#28 Added tts and stt into /voice endpoint
  app/Makefile
  app/backend/app.py
  app/backend/speech/speech_to_text.py
Labels: enhancement

#29 Frontend integrate endpoints (voice)
  app/backend/app.py
  app/backend/models/voice.py
  app/dev.sh
  app/frontend-healthier-me/src/app/app.config.ts
  app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.ts
  app/frontend-healthier-me/src/app/components/text/text-system/text-system.component.spec.ts
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/components/voice/voice.component.ts
  app/frontend-healthier-me/src/app/components/waveform/waveform.component.ts
  app/frontend-healthier-me/src/app/services/audio-player/audio-player.service.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/types/api/api-chat-history.type.ts
  app/frontend-healthier-me/src/app/types/api/api-profile.type.ts
  app/frontend-healthier-me/src/app/types/api/requests/voice-request.type.ts
  app/frontend-healthier-me/src/app/types/api/response/api-voice-response.type.ts
  app/frontend-healthier-me/src/app/types/message.type.ts
  app/frontend-healthier-me/src/app/types/profile.type.ts
  app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts
  app/frontend-healthier-me/src/app/utils/audio-recorder.ts
  app/frontend-healthier-me/src/app/utils/base-64-to-blob.ts
  app/frontend-healthier-me/src/app/utils/typed-form-data.ts
Labels: enhancement

#31 Link /voice endpoint to stt, tts, llm and frontend
  app/backend/app.py
  app/backend/models/voice.py
  app/backend/speech/text_to_speech.py
  app/backend/speech/translate.py
  app/backend/test/howtosleepbetter.wav
  app/backend/test/index.html
  app/backend/utils/__init__.py
  app/backend/utils/utils.py
Labels: enhancement

#35 Link voice endpoint with tts,stt and LLM
  app/Makefile
  app/backend/app.py
  app/backend/models/voice.py
  app/backend/speech/speech_to_text.py
  app/backend/speech/text_to_speech.py
  app/backend/speech/translate.py
  app/backend/test/howtosleepbetter.wav
  app/backend/test/index.html
  app/backend/utils/__init__.py
  app/backend/utils/utils.py
Labels: enhancement

#36 Frontend change conditions from open text to multiselect
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.html
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.ts
Labels: enhancement

#38 Frontend -- Updated to facilitate latest endpoint schema
  app/backend/test/index.html
  app/frontend-healthier-me/src/app/services/audio-player/audio-player.service.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/types/api/api-chat-history.type.ts
  app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts
Labels: enhancement

#40 Frontend -- fixed bug for loading chat for general profile
  app/frontend-healthier-me/src/app/components/text/text-input/text-input.component.ts
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/services/profile/profile.service.ts
Labels: bug

#42 Frontend -- shows conversation on the left of voice
  app/frontend-healthier-me/src/app/components/text/text-system/text-system.component.html
  app/frontend-healthier-me/src/app/components/text/text-user/text-user.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/components/voice/voice.component.html
  app/frontend-healthier-me/src/app/components/voice/voice.component.ts
  app/frontend-healthier-me/src/app/services/preference/preference.service.ts
  app/frontend-healthier-me/src/app/types/configs/preference-keys.type.ts
Labels: enhancement

#45 Frontend qol
  app/frontend-healthier-me/public/favicon.svg
  app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/directives/stick-bottom/sticky-bottom.directive.spec.ts
  app/frontend-healthier-me/src/app/directives/stick-bottom/sticky-bottom.directive.ts
  app/frontend-healthier-me/src/index.html
Labels: enhancement

#46 Frontend -- reduced navbar flicker
  app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.html
Labels: bug

#47 Frontend
  app/backend/test/index.html
  app/frontend-healthier-me/public/favicon.svg
  app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.html
  app/frontend-healthier-me/src/app/components/text/text-input/text-input.component.ts
  app/frontend-healthier-me/src/app/components/text/text-system/text-system.component.html
  app/frontend-healthier-me/src/app/components/text/text-user/text-user.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/components/voice/voice.component.html
  app/frontend-healthier-me/src/app/components/voice/voice.component.ts
  app/frontend-healthier-me/src/app/directives/stick-bottom/sticky-bottom.directive.spec.ts
  app/frontend-healthier-me/src/app/directives/stick-bottom/sticky-bottom.directive.ts
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.html
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.ts
  app/frontend-healthier-me/src/app/services/audio-player/audio-player.service.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/services/preference/preference.service.ts
  app/frontend-healthier-me/src/app/services/profile/profile.service.ts
  app/frontend-healthier-me/src/app/types/api/api-chat-history.type.ts
  app/frontend-healthier-me/src/app/types/configs/preference-keys.type.ts
  app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts
  app/frontend-healthier-me/src/index.html
Labels: enhancement

#51 Fix VAD dropping out
  app/frontend-healthier-me/src/app/services/vad/vad.service.ts
Labels: bug

#53 Frontend chat integration and QoL improvements
  app/backend/utils/utils.py
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/services/vad/vad.service.ts
  app/frontend-healthier-me/src/app/types/api/requests/chat-request.type.ts
  app/frontend-healthier-me/src/app/types/api/response/api-chat-response.type.ts
Labels: bug, enhancement

#54 Added new prompt
  app/backend/approaches/chatreadretrieveread.py
  app/backend/approaches/prompts.py
  app/backend/approaches/retrievethenread.py
Labels: enhancement

#55 Updated the sourcepage variable to sourcePage
  app/backend/approaches/approach.py
Labels: bug

#57 Minor updates
  app/backend/approaches/chatreadretrieveread.py
  app/backend/approaches/retrievethenread.py
  app/backend/prepdocslib/blobmanager.py
  app/backend/prepdocslib/embeddings.py
  app/backend/prepdocslib/integratedvectorizerstrategy.py
  app/backend/prepdocslib/searchmanager.py
Labels: enhancement

#62 Add shell script for azure startup and updated prompt
  app/backend/approaches/prompts.py
  app/backend/setup.sh
  app/backend/utils/utils.py
  app/start.ps1
Labels: enhancement

#68 Updated lint actions for frontend
  .github/workflows/frontend.yaml
  app/frontend-healthier-me/package.json
Labels: enhancement

#69 Refactor app.py
  app/backend/app.py
  app/backend/blueprints/backend_blueprint/__init__.py
  app/backend/blueprints/backend_blueprint/chat.py
  app/backend/blueprints/backend_blueprint/speech.py
  app/backend/blueprints/backend_blueprint/upload.py
  app/backend/blueprints/backend_blueprint/voice.py
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.html
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.spec.ts
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.ts
  app/frontend-healthier-me/src/app/components/text/text-tts/text-tts.component.ts
  app/frontend-healthier-me/src/app/components/text/text.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.spec.ts
  app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/types/api/requests/speech-request.type.ts
  app/frontend-healthier-me/src/app/types/follow-up.type.ts
Labels: enhancement

#93 Fixed live transcription and update frontend ui
  .pre-commit-config.yaml
  app/backend/approaches/config.py
  app/backend/approaches/prompts.py
  app/backend/blueprints/backend_blueprint/transcription.py
  app/backend/models/chat_history.py
  app/backend/models/feedback.py
  app/backend/speech/speech_to_text.py
  app/backend/utils/utils.py
  app/frontend-healthier-me/src/app/app.component.ts
  app/frontend-healthier-me/src/app/app.routes.ts
  app/frontend-healthier-me/src/app/components/navbar-mobile/navbar-mobile.component.html
  app/frontend-healthier-me/src/app/components/navbar-mobile/navbar-mobile.component.ts
  app/frontend-healthier-me/src/app/components/navbar/navbar-language/navbar-language.component.html
  app/frontend-healthier-me/src/app/components/navbar/navbar-language/navbar-language.component.ts
  app/frontend-healthier-me/src/app/components/navbar/navbar-logo-group/navbar-logo-group.component.html
  app/frontend-healthier-me/src/app/components/text-mobile/text-mobile.component.html
  app/frontend-healthier-me/src/app/components/text-mobile/text-mobile.component.ts
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.css
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.html
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.spec.ts
  app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.ts
  app/frontend-healthier-me/src/app/components/text/text.component.html
  app/frontend-healthier-me/src/app/components/text/text.component.ts
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-annotation/voice-annotation.component.css
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-annotation/voice-annotation.component.html
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-annotation/voice-annotation.component.ts
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.html
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.ts
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.html
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.ts
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-sources/voice-sources.component.css
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-sources/voice-sources.component.html
  app/frontend-healthier-me/src/app/components/voice-mobile/voice-sources/voice-sources.component.ts
  app/frontend-healthier-me/src/app/layouts/main-layout/main-layout.component.html
  app/frontend-healthier-me/src/app/pages/chat/chat.component.html
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.html
  app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.ts
  app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.spec.ts
  app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.ts
  app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
  app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
  app/frontend-healthier-me/src/app/types/api/api-chat-history.type.ts
  app/frontend-healthier-me/src/app/types/api/requests/feedback-request.type.ts
  app/frontend-healthier-me/src/app/types/feedback.type.ts
  app/frontend-healthier-me/src/app/types/follow-up.type.ts
  app/frontend-healthier-me/src/app/types/language.type.ts
  app/frontend-healthier-me/src/app/utils/v2/audio-recorder-v2.ts
Labels: bug, enhancement
